# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Shoker2/Desktop/modpack_updater/app/ui/activate_mods_wndow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from pyqt_checkbox_list_widget.checkBoxListWidget import CheckBoxListWidget

class Ui_ActivateMods(QMainWindow):
    def __init__(self):
        super().__init__()

        self.setObjectName("Form")
        self.resize(500, 600)
        self.GeneralScrollArea = QtWidgets.QScrollArea(self)
        self.GeneralScrollArea.setGeometry(QtCore.QRect(10, 30, 531, 281))
        self.GeneralScrollArea.setWidgetResizable(True)
        self.GeneralScrollArea.setObjectName("GeneralScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 529, 279))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = CheckBoxListWidget()
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.GeneralScrollArea.setWidget(self.scrollAreaWidgetContents)

        QtCore.QMetaObject.connectSlotsByName(self)

        self.setWindowTitle("Активные моды")

        self.listWidget.checkedSignal.connect(self.checkstateChanged)

    def checkstateChanged(self, index, status):
        print(self.listWidget.item(index).text())

    def resizeEvent(self, event):
        self.GeneralScrollArea.setGeometry(0, 0, self.size().width(), self.size().height())
        return super().resizeEvent(event)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_ActivateMods()
    ui.show()
    sys.exit(app.exec_())
