# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Shoker2/Desktop/Pomariol Launcher/Resourses/ui/update_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

class Ui_Update(QMainWindow):
    progressBarSignal = QtCore.pyqtSignal(int)

    def __init__(self):
        super().__init__()

        self.setObjectName("Update")
        self.resize(500, 177)

        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.setMenuBar(self.menubar)

        self.actionSettings = QtWidgets.QAction(self)
        self.actionSettings.setObjectName("actionSettings")
        self.actionMods = QtWidgets.QAction(self)
        self.actionMods.setObjectName("action")
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionMods)
        self.menubar.addAction(self.menuFile.menuAction())

        self.GeneralScrollArea = QtWidgets.QScrollArea(self)
        self.GeneralScrollArea.setGeometry(QtCore.QRect(10, 10, 531, 261))
        self.GeneralScrollArea.setWidgetResizable(True)
        self.GeneralScrollArea.setObjectName("GeneralScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 529, 259))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.modpacksComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.modpacksComboBox.setObjectName("modpacksComboBox")
        self.verticalLayout_2.addWidget(self.modpacksComboBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.updateButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.updateButton.setFont(font)
        self.updateButton.setObjectName("updateButton")
        self.verticalLayout_2.addWidget(self.updateButton)
        self.progressBar = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.GeneralScrollArea.setWidget(self.scrollAreaWidgetContents)

        self.setWindowTitle("Обновление сборки")
        self.updateButton.setText("Обновить")

        self.menuFile.setTitle("Файл")
        self.actionSettings.setText("Настройки")
        self.actionMods.setText("Активация модов")

        self.progressBar.setTextVisible(False)
    
        self.progressBarSignal.connect(self.progressBarSignalEvent)
        self.updateButton.clicked.connect(self.updateButtonClicked)

        self.progressBarSignal.emit(0)
    
    def resizeEvent(self, event):
        self.GeneralScrollArea.setGeometry(0, 25, self.size().width(), self.size().height() - 25)
        return super().resizeEvent(event)
    
    def progressBarSignalEvent(self, value):
        self.progressBar.setValue(value)
    
    def updateButtonClicked(self):
        pass

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    ui = Ui_Update()
    ui.show()

    sys.exit(app.exec_())
